# Generated by Django 4.1.4 on 2022-12-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_no', models.IntegerField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store_Part',
            fields=[
                ('sp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('car_make', models.CharField(max_length=50)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Storepart', to='User.store')),
                ('part_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.part')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/StoreProfile/20221229-122206', width_field='imagewidth')),
                ('imagewidth', models.PositiveIntegerField(default=50, editable=False)),
                ('imageheight', models.PositiveIntegerField(default=50, editable=False)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreInformation', to='User.store')),
            ],
        ),
        migrations.CreateModel(
            name='Part_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/PartImages/20221229-122206', width_field='imagewidth')),
                ('imagewidth', models.PositiveIntegerField(default=65, editable=False)),
                ('imageheight', models.PositiveIntegerField(default=65, editable=False)),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.part')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_Part',
            fields=[
                ('op_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Storepart', to='Store.store_part')),
            ],
        ),
    ]
