# Generated by Django 4.1.4 on 2022-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_part_image_image_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/PartImages/20221229-122221', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/StoreProfile/20221229-122221', width_field='imagewidth'),
        ),
    ]
