# Generated by Django 4.1.4 on 2022-12-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='op_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.ordered_part'),
        ),
    ]
