# Generated by Django 4.0 on 2023-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP', '0002_alter_store_image_image_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dabrharequest',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='images/part/20230211-201000', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='workshop_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230211-201000', width_field='imagewidth'),
        ),
    ]
