# Generated by Django 4.0 on 2023-02-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP', '0003_remove_dabrharequest_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dabrharequest',
            name='has_an_offer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dabrharequest',
            name='img',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='media/part_images/', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='images/part/20230211-205435', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='workshop_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230211-205435', width_field='imagewidth'),
        ),
    ]
