# Generated by Django 4.0 on 2023-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP', '0004_dabrharequest_has_an_offer_dabrharequest_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dabrharequest',
            name='img',
            field=models.ImageField(default='no-image.jpg', upload_to='media/part_images/'),
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='images/part/20230212-141052', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='workshop_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230212-141052', width_field='imagewidth'),
        ),
    ]
