# Generated by Django 4.1.4 on 2022-12-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Store', '0003_alter_part_image_image_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop_Order',
            fields=[
                ('wo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Workshoporders', to='User.workshop')),
                ('op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.ordered_part')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/WorkShopProfile/20221229-122221', width_field='imagewidth')),
                ('imagewidth', models.PositiveIntegerField(default=50, editable=False)),
                ('imageheight', models.PositiveIntegerField(default=50, editable=False)),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopImg', to='User.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopServices', to='User.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('offer_desc', models.CharField(max_length=200)),
                ('offer_price', models.IntegerField()),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopOffers', to='User.workshop')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.service')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerAppointment', to='User.workshop')),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopAppointment', to='User.workshop')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.service')),
            ],
        ),
    ]
